/** Mirror of petpet-service `App\Constants\PermissionConstant`. Keep the two in sync. */
export const PERMISSION = {
  EVENT_VIEW: "event.view",
  EVENT_CREATE: "event.create",
  EVENT_UPDATE: "event.update",
  EVENT_DELETE: "event.delete",
  EVENT_PUBLISH: "event.publish",
  COMPETITION_VIEW: "competition.view",
  COMPETITION_CREATE: "competition.create",
  COMPETITION_UPDATE: "competition.update",
  COMPETITION_DELETE: "competition.delete",
  REGISTRATION_VIEW: "registration.view",
  REGISTRATION_APPROVE: "registration.approve",
  REGISTRATION_REJECT: "registration.reject",
  PAYMENT_VIEW: "payment.view",
  PAYMENT_VERIFY: "payment.verify",
  PAYMENT_REFUND: "payment.refund",
  PAYOUT_VIEW: "payout.view",
  PAYOUT_REQUEST: "payout.request",
  PAYOUT_APPROVE: "payout.approve",
  SCORING_VIEW: "scoring.view",
  SCORING_INPUT: "scoring.input",
  SCORING_VERIFY: "scoring.verify",
  ORGANIZATION_VIEW: "organization.view",
  ORGANIZATION_MANAGE: "organization.manage",
  ORGANIZATION_VERIFY: "organization.verify",
  STAFF_INVITE: "staff.invite",
  STAFF_MANAGE: "staff.manage",
  USER_VIEW: "user.view",
  USER_MANAGE: "user.manage",
  MASTER_MANAGE: "master.manage",
  PLATFORM_SETTINGS: "platform.settings",
} as const;

export type Permission = (typeof PERMISSION)[keyof typeof PERMISSION];
